apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: devtestlab/v1beta1/globalvmshutdownschedule
    uptest.upbound.io/pre-delete-hook: testhooks/delete-network.sh
  labels:
    testing.upbound.io/example-name: example
  name: platform-engineering-test
spec:
  forProvider:
    location: "Sweden Central"