apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: sandbox-subnet
  labels:
    name: sandbox-subnet
spec:
  forProvider:
    region: eu-west-3
    availabilityZone: eu-west-3a
    vpcIdSelector:
      matchLabels:
        name: sandbox-vpc
    cidrBlock: 10.0.0.0/17
  providerConfigRef:
    name: aws-provider-config