---
apiVersion: sgt.com/v1alpha1
kind: ClusterClaim
metadata:
  name: NAME
  namespace: sgt-apps
spec:
  id: NAME
  compositionSelector:
    matchLabels:
      provider: PROVIDER
      cluster: CLUSTER
  parameters:
    nodeSize: SIZE
    minNodeCount: 1
