apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: sgt-dynamodb-with-bucket
spec:
  compositeTypeRef:
    apiVersion: sgt.com/v1alpha1
    kind: XSgtNoSqlDatabase
  resources:
    - name: s3Bucket
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        metadata:
          name: sgt-apps-bucket
        spec:
          forProvider:
            name: default
            region: "af-south-1"
      patches:
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
          transforms:
            - type: map
              map: 
                EU: "eu-north-1"
                ZA: "af-south-1"
    - name: dynamoDB
      base:
        apiVersion: dynamodb.aws.upbound.io/v1beta1
        kind: Table
        metadata:
          name: sgt-apps-database
        spec:
          forProvider:
            writeCapacity: 1
            readCapacity: 1
            attribute:
              - name: S3ID
                type: S
            hashKey: S3ID
            region: "af-south-1"
      patches:
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
          transforms:
            - type: map
              map: 
                EU: "eu-west-1"
                ZA: "af-south-1"