apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: noqsldatabases.sgt.com
spec:
  group: sgt.com
  names:
    kind: XSgtNoSqlDatabase
    plural: XSgtNoSqlDatabases
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              region:
                type: string
                oneOf:
                  - pattern: '^EU$'
                  - pattern: '^ZA$'
            required:
              - region
  claimNames:
    kind: sgt-nosql-database
    plural: sgt-nosql-databases
 