apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: sqldatabases.sgt.com
spec:
  group: sgt.com
  names:
    kind: XSgtSqlDatabase
    plural: XSgtSqlDatabases
  connectionSecretKeys:
  - username
  - password
  - endpoint
  - port
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              version:
                type: string
                enum:
                - "15"
                - "16.1"
                default: "16.1"
            required:
            - version
  claimNames:
    kind: SgtSqlDatabase
    plural: sgt-sqldatabases