apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsgtvirtualmachines.sgt.com
spec:
  group: sgt.com
  names:
    kind: XSgtVirtualMachine
    plural: xsgtvirtualmachines
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              region:
                type: string
                oneOf:
                  - pattern: '^EU$'
                  - pattern: '^ZA$'
            required:
              - region
  claimNames:
    kind: SgtVirtualMachine
    plural: sgt-virtualmachines
