apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: rediscaches.sgt.com
spec:
  group: sgt.com
  names:
    kind: rediscache
    plural: rediscaches
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              version:
                type: string
                default: "6"
            required:
            - version
  claimNames:
    kind: sgt-rediscache
    plural: sgt-rediscaches