name: Create a Postgres DB
on:
  workflow_dispatch:
    inputs:
      request:
        description: "Action to perform (apply/destroy)"
        required: true
        default: "destroy"
      name:
        required: true
        description: "The name of the postgres db"
      vpc:
        required: false
        description: "VPC Id"
      version:
        type: string
        required: true
        description: "The version of the Engine"
        default: "11"


env:
  name: ${{ inputs.name }}
  version: ${{ inputs.version }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_VPC: ${{secrets.AWS_ACCESS_VPC_ID }}
  PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
  PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
  ACTION: ${{ github.event.inputs.request }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.request == 'create'}}
    defaults:
      run:
        shell: bash
        working-directory: ./platform/terraform/rds
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: print variables
        run: "default vpc: ${{ env.AWS_DEFAULT_VPC }}  ${{secrets.AWS_ACCESS_VPC_ID }}" 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        id: terraform_apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_vpc_id: ${{inputs.vpc}}
      
  create-db:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.request == 'create'}}
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Create Postgres DB
        run: |
          chmod +x platform/helpers/create-postgres.sh
          ./platform/helpers/create-postgres.sh ${{ env.name }} ${{ env.version }}
      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Create postgres ${{ env.name }} "
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ORG_TOKEN }}
          branch: ${{ github.ref }}

  teardown:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.request == 'delete'}}
    defaults:
      run:
        shell: bash
        working-directory: ./platform/terraform/rds

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Destroy
        id: terraform_destroy
        run: terraform destroy -auto-approve
        env:
          TF_VAR_vpc_id: ${{ env.AWS_DEFAULT_VPC }}    
